baseURL: "https://oden.gr"
languageCode: "en-us"
title: "Vaios Karampinis"

enableEmoji: true

params:
  author: "Vaios Karampinis"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Blog"
      url: "/blog/"
      weight: 2
    - name: "Running"
      url: "/running/"
      weight: 3
